[package]
name = "pallet-session-manager"
version = "0.1.0"
authors = ["Aleksandr Krupenkin <aleksandr@stake.co.jp>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.0", features = ["derive"], default-features = false }
rstd = { package = "sr-std", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }
support = { package = "frame-support", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }
system = { package = "frame-system", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }
session = { package = "pallet-session", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }

[dev-dependencies]
sr-io = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
primitives = { package = "substrate-primitives", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
timestamp = { package = "pallet-timestamp", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
sr-primitives = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "rstd/std",
    "support/std",
    "system/std",
    "session/std",
]
