[package]
name = "plasm-testing"
version = "0.4.9"
authors = ["Takumi Yamashita <takumi@staked.co.jp>"]
description = "Test utilities for Substrate node."
edition = "2018"

[dependencies]
balances = { package = "srml-balances", git = "https://github.com/satellitex/substrate.git" }
client = { package = "substrate-client", git = "https://github.com/satellitex/substrate.git" }
contracts = { package = "srml-contracts", git = "https://github.com/satellitex/substrate.git" }
grandpa = { package = "srml-grandpa", git = "https://github.com/satellitex/substrate.git" }
indices = { package = "srml-indices", git = "https://github.com/satellitex/substrate.git" }
keyring = { package = "substrate-keyring", git = "https://github.com/satellitex/substrate.git" }
plasm-executor = { path = "../executor" }
plasm-primitives = { path = "../primitives" }
plasm-runtime = { path = "../runtime" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
primitives = { package = "substrate-primitives", git = "https://github.com/satellitex/substrate.git" }
sr-io = { git = "https://github.com/satellitex/substrate.git" }
sr-primitives = { git = "https://github.com/satellitex/substrate.git" }
runtime_support = { package = "srml-support", git = "https://github.com/satellitex/substrate.git" }
session = { package = "srml-session", git = "https://github.com/satellitex/substrate.git" }
staking = { package = "srml-staking", git = "https://github.com/satellitex/substrate.git" }
substrate-executor = { git = "https://github.com/satellitex/substrate.git" }
system = { package = "srml-system", git = "https://github.com/satellitex/substrate.git" }
test-client = { package = "substrate-test-client", git = "https://github.com/satellitex/substrate.git" }
timestamp = { package = "srml-timestamp", git = "https://github.com/satellitex/substrate.git" }
treasury = { package = "srml-treasury", git = "https://github.com/satellitex/substrate.git" }
wabt = "~0.7.4"
