[package]
name = "deposit-abi-gen"
version = "0.1.0"
authors = ["Takumi Yamashita <takumi@staked.co.jp>"]
edition = "2018"
publish = false

[[bin]]
name = "deposit-abi-gen"
path = "main.rs"

[dependencies]
contract = { path = "../..", package = "deposit", features = ["ink-generate-abi", "test-env"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
