[package]
name = "pallet-plasm-validator"
version = "0.1.0"
authors = [
    "Takumi Yamashita <takumi@stake.co.jp>",
    "Aleksandr Krupenkin <aleksandr@stake.co.jp>"
]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3", features = ['derive'], default-features = false }
serde = { version = "1.0", optional = true }

sp-core = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
sp-runtime = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
sp-arithmetic = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
sp-io = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
sp-std = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
pallet-balances = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
frame-support = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
frame-system = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }
sp-staking = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty", default_features = false }

pallet-plasm-rewards = { path = '../plasm-rewards', default_features = false }

[dev-dependencies]
hex-literal = "0.2.1"
pallet-timestamp = { git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty" }
pallet-session = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-dusty" }
randomness-collective-flip = { package = "pallet-randomness-collective-flip", git = 'https://github.com/staketechnologies/substrate.git', branch = "plasm-dusty" }

[features]
default = ["std"]
std = [
    'codec/std',
    'sp-core/std',
    'sp-runtime/std',
    'sp-arithmetic/std',
    'sp-io/std',
    'sp-std/std',
    'pallet-balances/std',
    'frame-support/std',
    'frame-system/std',
    'sp-staking/std',
    'serde/std',
    'pallet-plasm-rewards/std',
]
