[package]
name = "plasm-rpc"
version = "1.7.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
edition = "2018"

[dependencies]
plasm-runtime = { path = "../runtime" }
plasm-primitives = { path = "../primitives" }
frontier-rpc = { path = "../../../vendor/frontier/rpc" }
frontier-rpc-primitives = { path = "../../../vendor/frontier/rpc/primitives" }
jsonrpc-core = "15.0.0"
jsonrpc-pubsub = "15.0.0"
sp-api = "2.0.0"
sp-runtime = "2.0.0"
sp-blockchain = "2.0.0"
sp-block-builder = "2.0.0"
sp-consensus = "0.8.0"
sp-consensus-babe = "0.8.0"
sp-transaction-pool = "2.0.0"
sc-rpc = "2.0.0"
sc-rpc-api = "0.8.0"
sc-keystore = "2.0.0"
sc-client-api = "2.0.0"
sc-consensus-babe = "0.8.0"
sc-consensus-babe-rpc = "0.8.0"
sc-consensus-epochs = "0.8.0"
sc-finality-grandpa = "0.8.0"
sc-finality-grandpa-rpc = "0.8.0"
sc-network = "0.8.0"
pallet-contracts-rpc = "0.8.0"
pallet-transaction-payment-rpc = "2.0.0"
substrate-frame-rpc-system = "2.0.0"
