[package]
name = "plasm-rpc"
version = "0.6.2"
authors = [
    "Takumi Yamashita <takumi@stake.co.jp>",
    "Aleksandr Krupenkin <aleksandr@stake.co.jp>"
]
edition = "2018"

[dependencies]
jsonrpc-core = "14.0.3"
plasm-runtime = { path = "../runtime" }
plasm-primitives = { path = "../primitives" }
client = { package = "sc-client", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
sp-runtime = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
pallet-contracts-rpc = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
pallet-transaction-payment-rpc = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
substrate-frame-rpc-system = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
