[package]
name = "plasm-rpc"
version = "0.9.9"
authors = [
    "Takumi Yamashita <takumi@stake.co.jp>",
    "Aleksandr Krupenkin <aleksandr@stake.co.jp>"
]
edition = "2018"

[dependencies]
plasm-runtime = { path = "../runtime" }
plasm-primitives = { path = "../primitives" }
jsonrpc-core = "14.0.3"
sp-api = "2.0.0-alpha.6"
sp-runtime = "2.0.0-alpha.6"
sp-blockchain = "2.0.0-alpha.6"
sp-consensus = "0.8.0-alpha.6"
sp-consensus-babe = "0.8.0-alpha.6"
sp-transaction-pool = "2.0.0-alpha.6"
sc-client = "0.8.0-alpha.6"
sc-keystore = "2.0.0-alpha.6"
sc-consensus-babe = "0.8.0-alpha.6"
sc-consensus-babe-rpc = "0.8.0-alpha.6"
sc-consensus-epochs = "0.8.0-alpha.6"
pallet-contracts-rpc = "0.8.0-alpha.6"
pallet-transaction-payment-rpc = "2.0.0-alpha.6"
substrate-frame-rpc-system = "2.0.0-alpha.6"
