[package]
name = "plasm-rpc"
version = "1.2.2"
authors = ["Stake Technologies <devops@stake.co.jp>"]
edition = "2018"

[dependencies]
plasm-runtime = { path = "../runtime" }
plasm-primitives = { path = "../primitives" }
jsonrpc-core = "14.0.3"
sp-api = "2.0.0-rc4"
sp-runtime = "2.0.0-rc4"
sp-blockchain = "2.0.0-rc4"
sp-block-builder = "2.0.0-rc4"
sp-consensus = "0.8.0-rc4"
sp-consensus-babe = "0.8.0-rc4"
sp-transaction-pool = "2.0.0-rc4"
sc-rpc-api = "0.8.0-rc4"
sc-keystore = "2.0.0-rc4"
sc-client-api = "2.0.0-rc4"
sc-consensus-babe = "0.8.0-rc4"
sc-consensus-babe-rpc = "0.8.0-rc4"
sc-consensus-epochs = "0.8.0-rc4"
sc-finality-grandpa = "0.8.0-rc4"
sc-finality-grandpa-rpc = "0.8.0-rc4"
pallet-contracts-rpc = "0.8.0-rc4"
pallet-transaction-payment-rpc = "2.0.0-rc4"
substrate-frame-rpc-system = "2.0.0-rc4"
