[package]
name = "kylin-oracle"
authors = ['Kylin <https://github.com/kylin-network>']
description = "oracle for fetch data from datasource"
version = '3.0.0'
license = 'Apache 2.0'
homepage = 'https://substrate.dev'
repository = "https://github.com/kylin-network/kylin-node"
edition = '2018'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false, optional = true }
frame-support = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.7", default-features = false }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.7" }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.7", default-features = false }

[dev-dependencies]
serde = { version = "1.0.101" }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false}
sp-io = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.7", default-features = false }

[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking']
std = [
	"codec/std",
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
]
