[package]
name = "democracy-mbm"
version = "1.0.0"
license = "GPL-3.0-or-later"
description = "democracy pallet multi block migration to support async backing"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
astar-primitives = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
pallet-democracy = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-arithmetic = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true }
pallet-migrations = { workspace = true }
pallet-preimage = { workspace = true }
pallet-scheduler = { workspace = true }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-io/std",
	"log/std",
	"scale-info/std",
	"parity-scale-codec/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking?/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"astar-primitives/std",
	"pallet-democracy/std",
	"pallet-preimage/std",
	"pallet-scheduler/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"astar-primitives/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

try-runtime = [
	"frame-support/try-runtime",
	"astar-primitives/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-scheduler/try-runtime",
]
