[package]
name = "plasm-rpc-client"
version = "0.4.9"
authors = ["Takumi Yamashita <takumi@staked.co.jp>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
futures = "0.1.26"
hyper = "0.12"
jsonrpc-core-client = { version = "13.1.0", features = ["http", "ws"] }
log = "0.4"
plasm-primitives = { path = "../primitives" }
substrate-rpc = { git = "https://github.com/satellitex/substrate.git" }
