[settings]
timeout = 1000

# Used to start 4 validator nodes and 2 collator nodes for a single parachain.

[relaychain]
default_command = "./polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

  [[relaychain.nodes]]
  name = "dave"
  validator = true

[[parachains]]
id = 1000
chain = "{{CHAIN}}"
cumulus_based = true

  [[parachains.collators]]
  name = "collator1"
  command = "./astar-collator"
  rpc_port=9944

  [[parachains.collators]]
  name = "collator2"
  command = "./astar-collator"
